services:
  diplomacy:
    image: ghcr.io/allan-dip/diplomacy:${TAG:-latest}
    container_name: diplomacy
    pull_policy: ${PULL_POLICY:-always}
    restart: always
    ports:
      - 3000:3000 # Web UI
      - 8432:8432 # Agent API
      - 8434-8600:8434-8600 # DAIDE server
    volumes:
      - .cache/maps/:/app/maps/
